# Generated by Django 2.1.5 on 2022-02-23 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0002_auto_20220223_0158'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
