# Generated by Django 2.1.5 on 2022-02-24 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0005_auto_20220223_2201'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PageAdmin',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
    ]
